amigo_secreto/config/routes.rb
AmigoSecreto::Application.routes.draw do
  

  resources :usuarios do
     resources :comentarios
  end

  root :to => 'usuarios#index'

end

amigo_secreto/app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  attr_accessible :body
  
  validates_presence_of :body
end

amigo_secreto/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :apelido, :sugestao
  validates_presence_of :apelido, :sugestao


  has_many :comentarios

end

amigo_secreto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

amigo_secreto/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @usuario = Usuario.find(params[:usuario_id])
    @comentario = @usuario.comentarios.create(params[:comentario])
    redirect_to usuario_path(@usuario)
    
    # respond_to do |format|
    #   if @comentario.save
    #     format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
    #     format.json { render json: @comentario, status: :created, location: @comentario }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @comentario.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

amigo_secreto/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to :action => "index" }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

amigo_secreto/app/helpers/application_helper.rb
module ApplicationHelper
end

amigo_secreto/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

amigo_secreto/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

amigo_secreto/app/views/comentarios/_comentario.html.erb
<div class="container well" style="margin-left:80pt">
	
<p>
  <b> Comentário: </b> </br>
  <%= comentario.body %>
</p>
</div>

amigo_secreto/app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

amigo_secreto/app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

amigo_secreto/app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.body %></td>
    <td><%= comentario.usuario %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

amigo_secreto/app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

amigo_secreto/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @comentario.usuario %>
</p>


<p>
  <b>Body:</b>
  <%= @comentario.body %>
</p>



<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

amigo_secreto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Amigo Secreto</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Main navigation fixed on top -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="../usuarios">
              DC - Amigo Secreto 
            </a>
        
            <ul class="nav">
              <li class="active">
                <a href="">Home</a>
              </li>
           <!--    <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            --> </ul>
        
        <!--     <ul class="nav pull-right">
              <li><a href="/usuarios/sign_up">Sign Up</a></li>
              <li class="dropdown">
                <a href="#"
                      class="dropdown-toggle"
                      data-toggle="dropdown">
                      Profile
                      <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
 -->
                    

                    <!-- <li><a href="#">Link</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li> -->
<!--                 </ul>
              </li>
            </ul>
 -->        </div>
      </div>
    </div>


<%= yield %>

</body>
</html>

amigo_secreto/app/views/usuarios/_form.html.erb
<div style="margin:auto; width:800px">
<%= form_for(@usuario, :html => {:class => 'form-horizontal well'}) do |f| %>
  
  <% if @usuario.errors.any? %>
    <div class="alert alert-error">
      Ocorreram <%= pluralize(@usuario.errors.count, "erros") %> ao salvar o participante: 
      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Participante</legend>
    <div class="control-group">
        <%= f.label :apelido , "Nome", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :apelido , :style=> 'width:500px' %>
        </div>
    </div>
   
    <div class="control-group">
      <%= f.label :sugestao, "Sugestão de presente", :class => 'control-label' %>

      <div class="controls">
        <%= f.text_area :sugestao ,:rows => '10' , :style=> 'width:500px' %>
      </div>
    </div>
   
 

    <div class="form-actions">
        <%= f.submit "Salvar" ,:class => "btn btn-primary" %>
         <%= link_to 'Voltar', usuarios_path , :class => 'btn btn-primary', :style=> 'color:white' %>

    </div>
  </div>
</fieldset>
<% end %>
</div>

amigo_secreto/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

amigo_secreto/app/views/usuarios/index.html.erb
<div class="container ">

<fieldset>
  <legend>Lista dos Participantes</legend>

  <table class="table table-striped table-hover table-bordered" style="width:800px">
    <tr>
      <th style="width:630px">Nome</th>
      <th></th>
    </tr>

  <% @usuarios.each do |usuario| %>
    <tr>
      <td><%= usuario.apelido %></td>
      <td><%= link_to 'Visualizar Sugestão', usuario , :class => 'btn btn-inverse btn-small', :style=> 'color:white' %></td>
      <!-- <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td> -->
   <!--   <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </tr>
  <% end %>
  </table>

</fieldset>
<br />

<%= link_to 'Novo Participante' , new_usuario_path, :class => 'btn btn-primary', :style=> 'color:white' %>

amigo_secreto/app/views/usuarios/new.html.erb
<%= render 'form' %>

amigo_secreto/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container well">
	<div class="control-group">
		<label class="control-label"><b> <%= @usuario.apelido %>: </b></label>
		<p><%= @usuario.sugestao %></p>
	</div>	
</div>

<% if @usuario.comentarios.any? %>
	<div class="container"><h4>Comentarios</h4></div>
  	<%= render @usuario.comentarios %>
	
<% end %>

<div class="container">

<%= form_for([@usuario, @usuario.comentarios.build]) do |f| %>
 
 
 <fieldset>
 	<legend>Enviar comentário</legend>
        <label>Comentário: </label>
        <div class="controls">
          <%= f.text_area :body, :cols => '500', :rows=> '4', :style=> 'width: 600px' %>
        </div>

   	<div class="form-actions">
        <%= f.submit "Salvar" ,:class => "btn btn-primary" %>
        <%= link_to 'Voltar', usuarios_path , :class => 'btn btn-primary', :style=> 'color:white' %>

    </div>
<% end %>
</div>


<!-- 
<%= link_to 'Edit', edit_usuario_path(@usuario) %>  -->